version: '2'
services:
  thelounge:
    image: ghcr.io/thelounge/thelounge:latest
    container_name: thelounge
    ports:
      - "3002:9000"
    restart: always
    volumes:
      - ./thelounge:/var/opt/thelounge # bind lounge config from the host's file system
